[project]
name = "boatstuff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jey Burrows", email = "jrb@jeymail.net" }
]
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "numbers-parser>=4.19.0",
    "python-snappy>=0.7.3",
]

[project.scripts]
boatstuff = "boatstuff:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
